site_name: bryanpoulin.dev
site_description: Home-Lab Documentation
site_author: Bryan Poulin
site_url: https://bryanpoulin.dev

repo_url: https://github.com/bryan-poulin/mkdocs-material-demo-1 
repo_name: bryan-pouiln/mkdocs-material-demo-1

# ignores absolute warnings we have
# warns on missing/broken links
validation:
  omitted_files: warn
  not_found: warn
  absolute_links: ignore
# fails to build on warnings
strict: false

copyright: |
  &copy; 2024 <a href="https://github.com/bryan-poulin" target="_blank" rel="noopener">Bryan Poulin LLC</a>

extra:
  analytics:
    provider: google
    property: G-503565128
  social:
    - icon: simple/youtube
      link: https://youtube.com/@bryanpoulin
    - icon: fontawesome/brands/github-alt
      link: https://github.com/bryan-poulin

# extra_css:
#   - stylesheets/extra.css

hooks:
  - hooks/socialmedia.py

extra_javascript: 
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:  
  - abbr # used for Tooltips
  - admonition
  - attr_list
  - footnotes
  - md_in_html # used for annotatons
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true

plugins:
  - blog:
      blog_dir: blog
      archive_date_format: yyyy
      archive_url_date_format: yyyy
      categories_allowed:
        - Tech
        - Lifestyle
      blog_toc: true
      post_url_format: "{slug}"
  # - git-committers:
  #     enabled: true
  #     repository: james-willett/jameswillett.dev
  #     branch: main
  #     token: !ENV GH_TOKEN
  # - glightbox:
  #     touchNavigation: false
  #     loop: false
  #     effect: zoom
  #     width: 100%
  #     height: auto
  #     zoomable: true
  #     draggable: true
  # - git-revision-date-localized:
  #     type: date
  #     fallback_to_build_date: false
  #     enable_creation_date: true
  #     enabled: true
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - tags:
      enabled: true
      tags_allowed:
        - technology
        - lifestyle updates
  # - rss:
  #     match_path: "blog/posts/.*"
  #     pretty_print: true
  #     rss_feed_enabled: true
  #     date_from_meta:
  #       as_creation: date.created
  #       as_update: date.updated

theme:
  name: material
  custom_dir: overrides
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.indexes
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    # - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow  
  language: en
  palette:
    - media: "(prefers-color-scheme: dark)"
      primary: indigo
      accent: blue
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      primary: indigo
      accent: blue
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  font:
    text: "Roboto"
    code: "Roboto Mono"
  favicon: assets/favicon.png
  logo: assets/logo.png

# nav:
#   - Home: index.md
#   - Infrastructure:
#     - Hardware: infrastructure/hardware.md
#     - Network Topology: infrastructure/network-topology.md
#     - Proxmox Setup: infrastructure/proxmox-setup.md
